version: 0.2
phases:
  install:
    commands:
      - apt-get update -y
      - apt install apt-transport-https ca-certificates curl software-properties-common -y
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
      - apt install docker-ce -y
      - apt-get install -y gnupg gnupg2 gnupg1 curl git
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "this is a codebuild"



